[package]
name = "word-condenser-kangaroo"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]

###### bump holochain dependencies here
holochain_client = { git = "https://github.com/holochain/holochain-client-rust", branch = "holochain-0.3.0-beta-dev.8" }
holochain = { version = "0.3.0-beta-dev.8", features = ["sqlite-encrypted"] }
holochain_types = "0.3.0-beta-dev.7"
holochain_zome_types = "0.3.0-beta-dev.6"
mr_bundle = "0.2.0"
######

either = "*"
futures = "0.3"
portpicker = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sodoken = "0.0.9"
tauri = { version = "1.4", features = ["shell-open", "devtools"] }
thiserror = "1"
uuid = "0.1.4"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
